name: Build and Create AppImage

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jichu4n/actions/setup-qt@v2
      with:
        qt-version: '5.15'  # Ajusta la versión de Qt según tu proyecto

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev libxkbcommon-x11-0 libxkbcommon-x11-0-dbg libxi-dev libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev libxtst-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libasound2-dev libdbus-1-dev

    - name: Compile the application
      run: qmake -makefile && make

    - name: Install AppImage tools
      run: sudo apt-get install -y desktop-file-utils file

    - name: Download and set up linuxdeployqt
      run: |
        curl -L -o linuxdeployqt "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod +x linuxdeployqt

    - name: Create AppImage
      run: |
        mkdir appdir
        cp path/to/your/compiled/application appdir/  # Ajusta esta línea según el nombre de tu archivo de salida
        ./linuxdeployqt appdir/path/to/your/compiled/application -appimage
