name: Build and Create AppImage

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      BUILD_DIR: 'build'  # Especifica la carpeta de compilación

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install Qt 6.3.1
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.3.1'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev libxkbcommon-x11-0 libxkbcommon-x11-0-dbg libxi-dev libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev libxtst-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libasound2-dev libdbus-1-dev

    - name: Create build directory
      run: mkdir $BUILD_DIR

    - name: Compile the application
      working-directory: $BUILD_DIR
      run: qmake -makefile ../ && make

    - name: Install AppImage tools
      run: sudo apt-get install -y desktop-file-utils file

    - name: Download and set up linuxdeployqt
      run: |
        curl -L -o linuxdeployqt "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod +x linuxdeployqt

    - name: Create AppImage
      working-directory: $BUILD_DIR
      run: |
        mkdir appdir
        cp build appdir/  # Ajusta esta línea según la ubicación del archivo de salida después de compilar
        ../linuxdeployqt appdir -appimage
