name: Build & Publish

on:
  push:
    tags:
      - 'v*'

env:
  SOURCE_DIR:   ${{ github.workspace }}
  DEB_DIR:		${{ github.workspace }}/deploy
  QT_VERSION:   6.5.2
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
          version:      ${{ env.QT_VERSION }}
          host:         linux
          target:       desktop
          arch:         gcc_64
          dir:          ${{ runner.temp }}
          modules:      qtwebengine qtwebchannel qtpositioning qtquick3d
          install-deps: true
          archives: qtbase qtwebengine
          setup-python: false
          tools: tools_ifw tools_qtcreator
          set-env: true
    
    - name: Create build directory
      run:  mkdir ${{ env.SOURCE_DIR }}/buildd
        
    - name: Build
      working-directory: ${{ env.SOURCE_DIR }}/buildd
      run:  |
            qmake -r ${{ env.SOURCE_DIR }}/QTradingview2.pro
            make

    - name: create package
      run: |
        mkdir -p .debpkg/usr/bin
        cp ${{ env.SOURCE_DIR }}/buildd/QTradingview2 .debpkg/usr/bin/
        cp -r ${{ env.DEB_DIR}}/usr/share .debpkg/usr/

    - uses: jiro4989/build-deb-action@v3
      with:
        package: qtradingview2
        package_root: .debpkg
        maintainer: katmai1
        version: ${{ github.ref }}
        arch: 'amd64'
        depends: 'libc6 (>= 2.2.1)'
        desc: ' QTradingview in C++ '

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: qtradingview*.deb
