name: C/C++ CI

on:
  push:
    branches: [ "master" ]

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.5.2
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
          version:      ${{ env.QT_VERSION }}
          host:         linux
          target:       desktop
          arch:         gcc_64
          dir:          ${{ runner.temp }}
          modules:      qtwebengine qtwebchannel
          setup-python: false
    
    - name: Create build directory
      run:  mkdir ${{ env.SOURCE_DIR }}/buildd
        
    - name: Build
      working-directory: ${{ env.SOURCE_DIR }}/buildd
      run:  |
            qmake -r ${{ env.SOURCE_DIR }}/QTradingview2.pro
            make
