name: Debian Package

on:
  push:
    tags:
      - 'v*'

env:
  SOURCE_DIR:   ${{ github.workspace }}
  BIN_FILE:		${{ github.workspace }}/builds/Linux_x64/release/QTradingview2
  DEB_DIR:		${{ github.workspace }}/deploy
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Update version
      run: |
        echo "const char* const APP_VERSION = \"$(git describe --tags --abbrev=0)\";" > version.h
        git config --global user.email "katmai.mobil@gmail.com"
        git config --global user.name "katmai"
        git add version.h
        git commit -m "Creando nueva version"
        git push
        
    - name: create package
      run: |
        mkdir -p .debpkg/usr/bin
        cp ${{ env.BIN_FILE }} .debpkg/usr/bin/
        cp -r ${{ env.DEB_DIR}}/usr/share .debpkg/usr/

    - uses: jiro4989/build-deb-action@v3
      with:
        package: qtradingview2
        package_root: .debpkg
        maintainer: katmai1
        version: ${{ github.ref }}
        arch: 'amd64'
        depends: 'libc6 (>= 2.2.1)'
        desc: ' QTradingview in C++ '

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: qtradingview*.deb
