name: Debian Package

on:
  push:
    tags:
      - 'v*'

env:
  SOURCE_DIR:   ${{ github.workspace }}
  BIN_FILE:		${{ github.workspace }}/builds/Linux_x64/release/QTradingview2
  DEB_DIR:		${{ github.workspace }}/deploy
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: create package
      run: |
          mkdir .debpkg
          cp ${{ env.DEB_DIR}}/* .debpkg/
          # echo "Version: 0.8.6" >> ${{ env.DEB_DIR }}/DEBIAN/control
          cp ${{ env.BIN_FILE }} .debpkg/usr/bin/qtradingview2
          dpkg-deb --build .debpkg qtradingview2.deb

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: qtradingview2.deb
