name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: create sample script
        run: |
          mkdir -p .debpkg/usr/bin/
          cp builds/Linux_x64/release/QTradingview2 .debpkg/usr/bin/qtradingview2
         
          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/DEBIAN
          echo -e "echo postinst" > .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst
      - uses: jiro4989/build-deb-action@v3
        with:
          package: qtradingview
          package_root: .debpkg
          maintainer: katmai1
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          depends: 'libc6 (>= 2.2.1)'
          desc: 'this is sample package.'
