name: Build and Package for Debian
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Qt 6.2.1
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.*'
        modules: qtwebengine qtwebchannel qtpositioning
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts libgl1-mesa-dev libxkbcommon-x11-0 libxi-dev libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev libxtst-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libasound2-dev libdbus-1-dev

    - name: Build the application
      run: qmake && make

    - name: Prepare DEBIAN folder
      run: |
        mkdir -p qtradingview2/usr/bin
        cp -r deploy/* qtradingview2/
        echo "Version: ${{github.ref_name}}" >> qtradingview2/DEBIAN/control
        cp QTradingview2 qtradingview2/usr/bin/

    - name: Package for Debian
      run: fakeroot dpkg-deb --build qtradingview2
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: debian-package
        path: qtradingview2.deb
