name: release

"on":
  push:
    tags:
      - 'v*.*.*'

env:
  APP_NAME: 'qtradingview2'
  MAINTAINER: 'katmai1'
  DESC: 'Tradingview app'

jobs:
  build-linux-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create sample script
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .rpmpkg/usr/bin
          cp builds/Linux_x64/release/QTradingview2 .debpkg/usr/bin/qtradingview2
          cp builds/Linux_x64/release/QTradingview2 .rpmpkg/usr/bin/qtradingview2
      - uses: jiro4989/build-deb-action@v3
        with:
          package: ${{ env.APP_NAME }}
          package_root: .debpkg
          maintainer: ${{ env.MAINTAINER }}
          version: ${{ github.ref }}
          arch: 'amd64'
          desc: '${{ env.DESC }}'

      - uses: jiro4989/build-rpm-action@v2
        with:
          summary: '${{ env.DESC }}'
          package: ${{ env.APP_NAME }}
          package_root: .rpmpkg
          maintainer: ${{ env.MAINTAINER }}
          version: ${{ github.ref }}
          arch: 'x86_64'
          desc: '${{ env.DESC }}'
